name = "FlightGNC"
uuid = "f141b7d0-6781-47a7-9266-a0707263841d"
authors = ["Namhoon Cho <nhcho91@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
